apiVersion: v1
kind: Service
metadata:
  name: invest-sml-api-svc
  namespace: investment 
spec:
  type: NodePort
  selector:
    app: invest-sml-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081 